### ISSUE TITLE
Authentication using OAuth

### ISSUE THREAD

**Issue by megawario** [megawario/awesome-sauce#31]
User should only be able to delete/edit things if authenticated.

Requirements:
- new optional field for auth in Adventure/Player Dialog (email) to relate signed in user with adventure.
- enable auth on selected URLs (update/delete Adventure/Player)

**Comment by tronjob** [comment]
Since we're using OAuth, the email field should not be needed, since we'd get that info directly from the provider, without the need to obtain data from the user directly.

We'll need to store the e-mail (or a token/hash representing the same) in the backend though.

The flow would be something like:

1 - user enters site and optionally logs in using one of the methods to be implemented (we'll need a login link in the main page)
2 - proceeds to create adventure / registering as a player
3 - if user is not logged in, a warning is shown that since he is not authenticated, he will be unable to change his aventure/registration later

I'm still investigating how best to implement this, so I'm open to ideas about how the flow would work better! :)

**Comment by megawario** [comment]
I like the proposed solution but the following should be made aware:

Using only the email as optional field when creating the user:
- User is not bothered with authentication

Using the proposed approach:
- When implementing the sending email notification, if the user is logged in, there is auth and we are sending the email to the correct person.
- Care should be given to not destroy app flow: when exiting the input form to login, when returning everything must be as it was, no deleted fields.

I agree with the approach proposed if the requirements are met.
